# 公共配置
# 使得/refresh不需要验权
management:
  security:
    enabled: false

# jwt相关的配置
token:
  jwt:
    key: a123456789
    # 发放者
    iss: bi-uaa
    # 有效期120分钟
    expm: 120

spring:
  # rabbitmq的地址 用户名 密码
  rabbitmq:
    host: 120.26.118.194
    username: guest
    password: '{cipher}54afbcfe3a6d23f52ff36c17104894ab199621c7dc709f55f209ff295e5bcfbd'
  sleuth:
    sampler:
      # 1、采样比例
      percentage: 1.0
  # 2、接口调用信息推送到这个zipkin服务
  zipkin: 
    base-url: http://120.26.118.194:9411

  cloud:
    loadbalancer:
      # 开启重试
      retry:
        enabled: true
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.47.61.175:3306/business_intelligence?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: Developer
    password: '{cipher}ee9ee4bcaf942314b8ce9bf4b66ca8439db1c8754f75b9f943e744a28fc2eb4776838c55604662ae200e54d0b0a4b82255af7f45d0c79644eab619a4dca287ed'
ribbon:
  # 配置ribbon超时时间
  ConnectTimeout: 5000
  ReadTimeout: 5000
  # 是否开启重试
  OkToRetryOnAllOperations: true
  # 重试期间，实例切换次数
  MaxAutoRetriesNextServer: 3
  # 当前实例重试次数
  MaxAutoRetries: 0

hystrix:
  threadpool:
    default:
      coreSize: 80
      maxQueueSize: 200
      queueSizeRejectionThreshold: 20
  command:
    # 这是默认的配置
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          thread:
            # 20秒超时
            timeoutInMilliseconds: 20000
      fallback:
        enabled: true
        isolation:
          semaphore:
            # 调用降级策略的并发量
            maxConcurrentRequests: 20
      circuitBreaker:
        enabled: true
        # 10秒内超过5个请求
        requestVolumeThreshold: 5
        # 错误率超过80，开启熔断
        errorThresholdPercentage: 80
        # 10秒后进入半开启
        sleepWindowInMilliseconds: 10000
      metrics:
        rollingStats:
          # 10秒统计一次
          timeInMilliseconds: 10000
          numBuckets: 10
custom:
  datasource:
    names: offline-mysql,offline-oracle
    offline-mysql:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.27.113.75:3306/bycx_bi
      username: bycx_bi
      password: bycx_bi
    online:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://rr-bp1lvuaxx414eav97o.mysql.rds.aliyuncs.com:3306/tk_online
      username: ol_read
      password: eETq0kKYXzBM97
mybatis:
  typeAliasesPackage: com.dongnaoedu.springcloud.*.*.dao
  mapperLocations: classpath:/mybatis/mapper/*/*.xml
