spring:
  cloud:
    # stream相关配置
    stream:
      default:
        # 消息内容序列化格式
        contentType: application/json
      # 通道设置
      bindings:
        # 短信通道相关配置
        sms-send:
          # 绑定具体的mq实现
          binder: mq1
          # 目的地
          destination: sms-send
          contentType: application/json
        # 订单事件
        order-event:
          binder: mq1
          contentType: application/json
      # 具体接入的mq实现 
      binders:
        # 命名为mq1，使用rabbitmq
        mq1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 120.26.118.194
                port: 5672
                username: guest
                password: guest
